### ISSUE TITLE
I want to work with Polkadot and Kusama. If anyone can train me on the coding side, I want to serve Dotsama.

### ISSUE THREAD

**Issue by burhank6161** [polkadot-fellows/manifesto#1]
Please ensure:
- [x] I have read and understood the [Fellowship Manifesto](https://github.com/polkadot-fellows/manifesto/blob/main/manifesto.pdf)
- [x] I understand that the Fellowship is for *individuals* who possess substantial expertise and experience regarding core Polkadot technologies.
- [x] I understand that writing a (non-core) pallet or deploying a (non-system) parachain does not by itself fulfil the requirements for Fellowship membership.

Please replace the "___" with your information:
- I expect my rank is at least 1 and at most 5.
- I have been substantially involved with the Polkadot core technology set for 3 years.
- My most substantial PR to a Polkadot core repository is: ___
- My earliest non-trivial PR to a Polkadot core repository is: ___

**Comment by gavofyork** [comment]
Please consider using the Polkadot forums or social media for such proposals.
